# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='league', to='events.League'),
            preserve_default=False,
        ),
    ]
