# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_team_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='sport',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sport', to='events.Sport'),
            preserve_default=False,
        ),
    ]
