# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 21:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_arena'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='arena',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='arena', to='events.Arena'),
            preserve_default=False,
        ),
    ]
