# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-07 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_arena'),
    ]

    operations = [
        migrations.AddField(
            model_name='arena',
            name='city',
            field=models.CharField(default='1', max_length=250),
            preserve_default=False,
        ),
    ]
