# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 14:00
from __future__ import unicode_literals

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_arena_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(null=True, upload_to=events.models.get_file_path),
        ),
    ]
